name: .NET Core Desktop

on:
  push:
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  cli-ubuntu-x64:
    name: cli-ubuntu
    runs-on: ubuntu-latest

    env:
      APP_NAME: stalker-gamma-gui
      PROJECT_FOLDER: stalker-gamma-cli
      PROJECT_NAME: stalker-gamma-cli.csproj
      CONFIGURATION: Release
      ARCHITECTURE: x64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Run Csharpier
        run: |
          dotnet tool restore
          dotnet csharpier check .

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Make Build
        run: make build -C build/linux VERSION=${{ steps.gitversion.outputs.AssemblySemFileVer }} ARCH=${{ env.ARCHITECTURE }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: stalker-gamma-cli.${{ steps.gitversion.outputs.SemVer }}+linux.${{ env.ARCHITECTURE }}
          path: build/linux/build/stalker-gamma-cli
          compression-level: 9
  
  cli-ubuntu-arm64:
    name: cli-ubuntu-arm64
    runs-on: ubuntu-22.04-arm
    
    env:
      APP_NAME: stalker-gamma-gui
      PROJECT_FOLDER: stalker-gamma-cli
      PROJECT_NAME: stalker-gamma-cli.csproj
      CONFIGURATION: Release
      ARCHITECTURE: arm64
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Run Csharpier
        run: |
          dotnet tool restore
          dotnet csharpier check .

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Make Build
        run: make build -C build/linux VERSION=${{ steps.gitversion.outputs.AssemblySemFileVer }} ARCH=${{ env.ARCHITECTURE }}
        
      - name: Download appimagetool
        run: curl https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-aarch64.AppImage -Lo appimagetool-aarch64.AppImage
        
      - name: Make AppImage
        run: |
          chmod +x appimagetool-aarch64.AppImage
          mkdir -p build/linux/stalker-gamma.AppDir/usr/bin/
          cp build/linux/build/stalker-gamma-cli/* build/linux/stalker-gamma.AppDir/usr/bin/
          ./appimagetool-aarch64.AppImage build/linux/stalker-gamma.AppDir          

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Stalker_GAMMA-aarch64.AppImage
          path: Stalker_GAMMA-aarch64.AppImage
          compression-level: 9

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: stalker-gamma-cli.${{ steps.gitversion.outputs.SemVer }}+linux.${{ env.ARCHITECTURE }}
          path: build/linux/build/stalker-gamma-cli
          compression-level: 9

  cli-macos:
    name: cli-macos
    runs-on: macos-latest
    env:
      APP_NAME: stalker-gamma-gui
      PROJECT_FOLDER: stalker-gamma-cli
      PROJECT_NAME: stalker-gamma-cli.csproj
      CONFIGURATION: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Run Csharpier
        run: |
          dotnet tool restore
          dotnet csharpier check .

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Make Build
        run: make build -C build/mac VERSION=${{ steps.gitversion.outputs.AssemblySemFileVer }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: stalker-gamma-cli.${{ steps.gitversion.outputs.SemVer }}+mac.arm64
          path: build/mac/build/stalker-gamma-cli
          compression-level: 9

  cli-windows:
    name: cli-windows
    runs-on: windows-latest
    env:
      APP_NAME: stalker-gamma-gui
      PROJECT_FOLDER: stalker-gamma-cli
      PROJECT_NAME: stalker-gamma-cli.csproj
      CONFIGURATION: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Csharpier
        run: |
          dotnet tool restore
          dotnet csharpier check .

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Build CLI
        run: build/win/build.bat ${{ steps.gitversion.outputs.AssemblySemFileVer }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: stalker-gamma-cli.${{ steps.gitversion.outputs.SemVer }}+win.x64
          path: build/win/build/stalker-gamma-cli
          compression-level: 9
